# This is a basic workflow to help you get started with Actions

name: RELEASE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow builds the Java app!
  # This workflow submites the release
  release:
    if: startsWith(github.event.head_commit.message, '[release]') == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Can build any Java version
    strategy:
      matrix:
        java: [ '11' ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Code Checkout
      - name: Code Checkout
        uses: actions/checkout@v2
      # Runs as Java
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      # Run commands using shell runner
      - name: Maven verify build
        run: |
          mvn -V --fail-fast --no-transfer-progress --batch-mode clean package -DskipTests
      # Get POM version
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(bash mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project
      # Get project name
      - name: Extract Maven Artifact ID
        run: echo ::set-output name=artifactId::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec)
        id: artifact
      #
      # Docker build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      #
      # Push to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      # Push to Github Secure Registry
      - name: Login to GitHub
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.artifact.outputs.artifactId }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.artifact.outputs.artifactId }}:${{ steps.project.outputs.version }}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.project.outputs.version }}
      - name: Build Dockerfile and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.artifact.outputs.artifactId }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.artifact.outputs.artifactId }}:${{ steps.project.outputs.version }}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.project.outputs.version }}
          labels: |
            tech.bananaz.app.version=${{ steps.project.outputs.version }}
            tech.bananaz.core.version=${{ steps.btCore.outputs.version }}
            tech.bananaz.maintainer=contact@bananaz.tech
            tech.bananaz.repo=https://github.com/${{ github.repository }}